apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2020-04-14T10:18:12Z"
  generation: 14
  labels:
    k8s-app: loki
    qcloud-app: loki
  name: loki
  namespace: metrics
  resourceVersion: "10208894032"
  selfLink: /apis/apps/v1beta2/namespaces/metrics/deployments/loki
  uid: 3f455ce6-7e39-11ea-8063-26214f2e3892
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: loki
      qcloud-app: loki
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: loki
        qcloud-app: loki
    spec:
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        image: ccr.ccs.tencentyun.com/dhub.wscn.com/loki:latest
        imagePullPolicy: Always
        name: loki
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/loki
          name: config
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: loki-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-14T10:18:12Z"
    lastUpdateTime: "2020-04-14T10:23:29Z"
    message: ReplicaSet "loki-794f49f6d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-14T10:32:14Z"
    lastUpdateTime: "2020-04-14T10:32:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 14
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
