apiVersion: v1
data:
  promtail.yaml: |-
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    client:
      url: http://loki.metrics:3100/loki/api/v1/push

    scrape_configs:
     - job_name: system
       pipeline_stages:
       - docker:
       static_configs:
       - targets:
          - 10.0.0.17
         labels:
          job: varlogcontainers
          host: 10.0.0.17
          __path__: /var/log/containers/*.log
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-14T10:45:57Z"
  name: promtail-config
  namespace: metrics
  resourceVersion: "10241463293"
  selfLink: /api/v1/namespaces/metrics/configmaps/promtail-config
  uid: 1fbad5c5-7e3d-11ea-8063-26214f2e3892
