apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "7"
  creationTimestamp: "2020-04-15T02:41:58Z"
  generation: 7
  name: promtail-daemonset
  namespace: metrics
  resourceVersion: "10241493055"
  selfLink: /apis/apps/v1beta2/namespaces/metrics/daemonsets/promtail-daemonset
  uid: ad8fbaa7-7ec2-11ea-8063-26214f2e3892
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: promtail
    spec:
      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yaml
        image: ccr.ccs.tencentyun.com/dhub.wscn.com/promtail:latest
        imagePullPolicy: Always
        name: promtail-container
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/docker/containers
          name: logs
        - mountPath: /etc/promtail
          name: promtail-config
        - mountPath: /var/log
          name: varlog
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: promtail-serviceaccount
      serviceAccountName: promtail-serviceaccount
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/docker/containers
          type: ""
        name: logs
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - configMap:
          defaultMode: 420
          name: promtail-config
        name: promtail-config
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 15
  desiredNumberScheduled: 15
  numberAvailable: 15
  numberMisscheduled: 0
  numberReady: 15
  observedGeneration: 7
  updatedNumberScheduled: 15
